### ISSUE TITLE
안녕하세요 ~ 해당 작업 관련 Fix 올려요 ~ 

### ISSUE THREAD

**Issue by StellaYA** [andrewmok-kor/greenp_ios_sdk_myelinsoft#1]
- 우선 문제는 Dependency를 건 PopupView와 TCA 관련 library가 버전 충돌이 나는거였습니다.
   - PopupView : macOS 11v
   - TCA Library : macOS 10_15v
- Build가 되도록 수정은 해놨으나 아마 그냥 사용하기는 좀 어려우실 수 있어요. 
  -  빌드는 되지만, 추가 수정은 더 하셔야할 수도 있단 의미입니다. ~
  (PopupView의 버전 Fix 및 기존 코드들도 이미 에러가 나고 있는 상황이더라고요 ~)
   - 그리고 정확하게는 iOS 15v을 target으로 하셨기 때문에, 실제 추가하신 코드들에서 iOS 16버전의 `@available`은 이슈가 있어요. ~
- Project 파일도 별도로 만들어보고, 지금 올려놓으신 repo에서 만들어서 수정해놨어요. 
- 다만 push 하려고 했더니 authentification 에러가 나서요. ~ 파일 첨부해 놨는데 혹시 이슈 있으시면 코멘트 달아주세요 ~
[greenp_ios_sdk_myelinsoft.zip](https://github.com/andrewmok-kor/greenp_ios_sdk_myelinsoft/files/13233778/greenp_ios_sdk_myelinsoft.zip)

```
fatal: Authentication failed for 'https://github.com/andrewmok-kor/greenp_ios_sdk_myelinsoft.git/'
```

**Comment by andrewmok-kor** [comment]
안녕하세요 답변이 우선 늦었습니다. 이렇게까지 지원 해주시다니 감사합니다.
첨부 해주신 파일들은 정상으로 다운받았습니다. 많은 도움 주셔서 감사드립니다!
